import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import LandingNavbar from "@/components/landing-navbar";
import ClientLayout from "@/components/ClientLayout";
import SupabaseProvider from '@/components/SupabaseProvider';

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Design Your Case",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <SupabaseProvider>
          <ClientLayout>{children}</ClientLayout>
        </SupabaseProvider>
      </body>
    </html>
  );
}
