import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import AuthSessionProvider from "./auth/auth-session-provider";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Design Your Case",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, session
}: Readonly<{
  children: React.ReactNode;
  session: any;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthSessionProvider session={session}>
          {children}
        </AuthSessionProvider>
      </body>
    </html>
  );
}
